CREATE TABLE `snmp_mibs` (
   `ID` INTEGER NOT NULL AUTO_INCREMENT,
   `VENDOR` VARCHAR(255) DEFAULT NULL,
   `URL` VARCHAR(255) DEFAULT NULL,
   `CHECKSUM` VARCHAR(255) DEFAULT NULL,
   `VERSION` VARCHAR(5) DEFAULT NULL,
   `PARSER` VARCHAR(5) DEFAULT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
ALTER TABLE `networks` ADD `MTU` VARCHAR(255) NULL DEFAULT NULL AFTER `SPEED`;
ALTER TABLE `download_available` ADD `DELETED` INT(1) NOT NULL DEFAULT '0' AFTER `ID_WK`;
ALTER TABLE `snmp_laststate` ADD `VIRTUALMACHINES` VARCHAR(255) NULL DEFAULT NULL AFTER `LOCALPRINTERS`;
CREATE TABLE `usbdevices` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HARDWARE_ID` INT(11) NOT NULL,
    `DESCRIPTION` VARCHAR(255) DEFAULT NULL,
    `INTERFACE` VARCHAR(255) DEFAULT NULL,
    `MANUFACTURER` VARCHAR(255) DEFAULT NULL,
    `SERIAL` VARCHAR(255) DEFAULT NULL,
    `TYPE` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;