-- Create save_query table
CREATE TABLE IF NOT EXISTS `save_query` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `QUERY_NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT default NULL,
    `PARAMETERS` TEXT NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;