-- Create history table
CREATE TABLE IF NOT EXISTS `history` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER` VARCHAR(255) NOT NULL,
    `DATETIME_ACTION` DATETIME NOT NULL,
    `ACTION` VARCHAR(255) NOT NULL,
    `TARGET` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;