-- Create layouts table
CREATE TABLE IF NOT EXISTS `layouts` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `LAYOUT_NAME` VARCHAR(255) NOT NULL,
    `USER` VARCHAR(255) NOT NULL,
    `TABLE_NAME` VARCHAR(255) NOT NULL,
    `COLUMNS` TEXT NOT NULL,
    `DESCRIPTION` VARCHAR(255) NULL,
    `VISIBLE_COL` TEXT NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;