UNLOCK TABLES;
DELETE FROM `config` WHERE NAME LIKE 'CONEX_LDAP_FILTER%';
UPDATE `config` SET TVALUE = 2 WHERE NAME = 'CONEX_LDAP_NB_FILTERS';
INSERT IGNORE INTO `config` (NAME, TVALUE) VALUES ('CONEX_LDAP_FILTER1', ''), 
('CONEX_LDAP_FILTER1_ROLE', ''), 
('CONEX_LDAP_FILTER2', ''), 
('CONEX_LDAP_FILTER2_ROLE', '');