DELETE FROM `layouts` WHERE `TABLE_NAME` = 'list_show_all';

ALTER TABLE `layouts` ADD COLUMN VISIBILITY_SCOPE VARCHAR(255) DEFAULT 'USER';
ALTER TABLE `layouts` ADD COLUMN GROUP_ID VARCHAR(255);
ALTER TABLE `layouts` CHANGE COLUMN USER CREATOR VARCHAR(255) NOT NULL;