UNLOCK TABLES;

DROP TABLE `batteries`;

CREATE TABLE `batteries` (
  `ID` int NOT NULL AUTO_INCREMENT, 
  `HARDWARE_ID` int NOT NULL,
  `CHEMISTRY` varchar(20) DEFAULT NULL,
  `CYCLES` int DEFAULT NULL,
  `DESCRIPTION` varchar(10) DEFAULT "N/A",
  `DESIGNCAPACITY` varchar(10) DEFAULT NULL,
  `DESIGNVOLTAGE` varchar(20) DEFAULT NULL,
  `ESTIMATEDCHARGEREMAINING` varchar(255) DEFAULT NULL,
  `MANUFACTURER` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `SERIALNUMBER` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`),
  KEY `NAME` (`NAME`),
  KEY `MANUFACTURER` (`MANUFACTURER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

